"""Add subscription fields to users

Revision ID: 52ca13dcf893
Revises: cd35b3969a81
Create Date: 2026-07-01 19:37:01.998888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ca13dcf893'
down_revision: Union[str, Sequence[str], None] = 'cd35b3969a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_tier', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subscription_ends_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_ends_at')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('subscription_tier')

    # ### end Alembic commands ###
